/**
 * .game source code generator.
 * Produces GAME DSL code from the animation recipe, using flowmap/mask/parallax builtins.
 */

import * as path from 'path';
import type { ImageRecipe, AnimationClass } from './types.js';

interface GenerateOptions {
  imageName: string;
  outputDir: string;
  maskNames: string[];
  hasWater: boolean;
  hasSky: boolean;
  hasVegetation: boolean;
}

/**
 * Generate .game source code for a living wallpaper.
 * Uses the recipe to configure each layer's animation parameters.
 */
export function generateGameSource(recipe: ImageRecipe, opts: GenerateOptions): string {
  const { imageName, outputDir, maskNames, hasWater, hasSky, hasVegetation } = opts;
  const baseName = path.basename(imageName, path.extname(imageName));
  const componentName = `living-${baseName}`.replace(/[^a-z0-9-]/gi, '-').toLowerCase();

  const lines: string[] = [];
  lines.push(`// Living Wallpaper — AI-generated from ${imageName}`);
  lines.push(`// Scene: ${recipe.scene_type}`);
  lines.push(`// Generated by GAME living-wallpaper pipeline`);
  lines.push('');
  lines.push(`cinematic "${componentName}" {`);

  // Texture declarations
  lines.push(`  texture "photo" from "${imageName}"`);
  lines.push(`  texture "depth" from "${baseName}-depth.png"`);

  if (hasWater) {
    lines.push(`  texture "flow" from "${baseName}-flow.png"`);
    lines.push(`  texture "mask_water" from "${baseName}-mask_water.png"`);
  }
  if (hasSky) {
    lines.push(`  texture "mask_sky" from "${baseName}-mask_sky.png"`);
  }
  if (hasVegetation) {
    lines.push(`  texture "mask_vegetation" from "${baseName}-mask_vegetation.png"`);
  }

  lines.push('');

  // Config layer with tunable parameters
  const waterRegion = recipe.regions.find(r => r.animation_class === 'water');
  const skyRegion = recipe.regions.find(r => r.animation_class === 'sky');
  const vegRegion = recipe.regions.find(r => r.animation_class === 'vegetation');

  lines.push('  layer config {');
  lines.push(`    parallax_strength: 0.02`);
  lines.push(`    orbit_speed: 0.12`);
  if (hasWater) {
    lines.push(`    water_speed: ${(waterRegion?.flow_speed ?? 0.3).toFixed(2)}`);
    lines.push(`    water_scale: ${((waterRegion?.warp_amount ?? 0.3) * 0.15).toFixed(3)}`);
  }
  if (hasSky) {
    lines.push(`    sky_speed: ${(skyRegion?.flow_speed ?? 0.1).toFixed(2)}`);
    lines.push(`    sky_strength: ${((skyRegion?.warp_amount ?? 0.15) * 0.04).toFixed(4)}`);
  }
  if (hasVegetation) {
    lines.push(`    veg_strength: ${((vegRegion?.warp_amount ?? 0.5) * 0.02).toFixed(4)}`);
  }
  lines.push('  }');
  lines.push('');

  // Base layer — depth parallax for subtle 3D
  lines.push('  // Base — depth parallax gives subtle 3D camera motion');
  lines.push('  layer base {');
  lines.push('    parallax("photo", depth: "depth", strength: parallax_strength, orbit_speed: orbit_speed)');
  lines.push('  }');

  // Water layer — flowmap animation
  if (hasWater) {
    lines.push('');
    lines.push('  // Water — flows via AI-generated flowmap');
    lines.push('  layer water {');
    lines.push('    flowmap("photo", flow: "flow", speed: water_speed, scale: water_scale)');
    lines.push('    | mask("mask_water")');
    lines.push('  }');
  }

  // Sky layer — slow drift
  if (hasSky) {
    lines.push('');
    lines.push('  // Sky — slow horizontal drift');
    lines.push('  layer sky {');
    lines.push(`    distort(scale: 0.8, speed: sky_speed, strength: sky_strength)`);
    lines.push('    | sample("photo")');
    lines.push('    | mask("mask_sky")');
    lines.push('  }');
  }

  // Vegetation layer — organic sway
  if (hasVegetation) {
    lines.push('');
    lines.push('  // Vegetation — organic sway');
    lines.push('  layer vegetation {');
    lines.push(`    warp(scale: 1.5, octaves: 2, persistence: 0.5, strength: veg_strength)`);
    lines.push(`    | distort(scale: 2.0, speed: 0.15, strength: veg_strength * 0.5)`);
    lines.push('    | sample("photo")');
    lines.push('    | mask("mask_vegetation")');
    lines.push('  }');
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
